apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency
scopes:
  # optionally scope the policy to specific apps
spec:
  policies:
    timeouts:
      short: 1s

    retries:
      # retry policy definitions

    circuitBreakers:
      # circuit breaker policy definitions

  targets:
    apps:
      # vehicleregistrationservice:
      #   timeout: short

    actors:
      # actor types and their applied policies here

    components:
      # components and their applied policies here